### ISSUE TITLE
Create order plus

### ISSUE THREAD

**Issue by asundberg** [EmilyClaire/Feminist-Toolkits#9]
When you add an item to an order it creates a column for price at purchase and number of items, subtotal

INSTRUCTIONS:
Orders must belong to a user OR guest session (authenticated vs unauthenticated)
Orders must contain line items that capture the price, current product ID and quantity
If a user completes an order, that order should keep the price of the item at the time when they checked out even if the price of the product later changes

**Comment by sarahwelzgeselowitz** [comment]
http://docs.sequelizejs.com/en/1.7.0/docs/associations/
^thanks Stephanie

**Comment by sarahwelzgeselowitz** [comment]
^ I really wanna do this one since I don't quite understand it and I want to
